dist: trusty
sudo: required
language: c
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential libhiredis-dev libhiredis0.10
  - sudo apt-get install perlbrew
  - cpanm -S install Test::Nginx Test::Nginx::Socket
services:
  - redis-server
script:
  - make bootstrap
  - make test
branches:
  only:
    - master
